INSERT INTO `states` ( `StateName`) VALUES
('Andaman and Nicobar Islands'),
('Andhra Pradesh'),
('Arunachal Pradesh'),
('Assam'),
('Bihar'),
('Chandigarh'),
('Chhattisgarh'),
('Dadra and Nagar Haveli'),
('Daman and Diu'),
('Delhi-NCR'),
('Goa'),
('Gujarat'),
('Haryana'),
('Himachal Pradesh'),
('Jammu and Kashmir'),
('Jharkhand'),
('Karnataka'),
('Kenmore'),
('Kerala'),
('Lakshadweep'),
('Madhya Pradesh'),
('Maharashtra'),
('Manipur'),
('Meghalaya'),
('Mizoram'),
('Nagaland'),
('Narora'),
('Natwar'),
('Odisha'),
('Paschim Medinipur'),
('Pondicherry'),
('Punjab'),
('Rajasthan'),
('Sikkim'),
('Tamil Nadu'),
('Telangana'),
('Tripura'),
('TEST'),
('UP-1'),
('xxxxxx'),
('West Bengal'),
('UP-2');